%YAML 1.2
# List mapping files and assign type of file.
# The mapping type tells the importer what validation checks to perform.
#expect_event: true
#expect_unit: true
#expect_value: false
---
mappingApproaches:
  - &numeric
    name: numeric
  - &discrete
    name: discrete
  - &valueOnly
    name: value_only
  # TODO: by value as number, value as concept, value as date, value as text
  - &date
    name: date
  - &mappingTable
    name: mapping_table

mappings:
  - filename: date_field_lookup.csv
    mappingApproach: *date
    default_date_field: 53  # for fields not listed in the lookup

  - filename: numeric_fields.csv
    mappingApproach: *numeric

  - filename: discrete_fields.csv
    mappingApproach: *discrete

  - filename: 20001_cancer.csv
    mappingApproach: *valueOnly
    event_concept_id: 4214956 # History of clinical finding in subject (SNOMED)

  - filename: 20002_non-cancer_illness.csv
    mappingApproach: *valueOnly
    event_concept_id: 4214956 # History of clinical finding in subject (SNOMED)

  - filename: 20003_treatment_medication.csv
    mappingApproach: *valueOnly
    event_concept_id: 4059354 # H/O: regular medication (SNOMED)

  - filename: 20004_operation.csv
    mappingApproach: *valueOnly
    event_concept_id: 4215685 # Past history of procedure (SNOMED)

  - filename: ../mapping_tables/opcs3.csv
    mappingApproach: *mappingTable
    field_ids: [41256,41258,41273]
    event_concept_id: 4215685 # Past history of procedure (SNOMED)

  # Add reference to new mapping files here
