-- Does not get mapping of answer to std concept and does not use pre-coordinated pairs.
select
    source.concept_id,
    source.concept_code as "sourceCode",
    source.concept_name as "sourceName",
    answer_value as "sourceValueCode",
    source.answer_name as "sourceValueName",
    '' as "sourceUnitName",
    -1 as "sourceFrequency",
    '' as "sourceAutoAssignedConceptIds",
    0 as "matchScore",
    'EQUIVALENT' as "equivalence",
    'APPROVED' as "mappingStatus",
    'maxim' as "statusSetBy",
    round(extract(epoch from now())) as "statusSetOn",
    target.concept_id as "conceptId",
    target.concept_name as "conceptName",
    target.domain_id as "domainId",
    upper(replace(relationship_id, ' ', '_')) as "mappingType",
    '' as "comment",
    '<athena>' as "createdBy",
    round(extract(epoch from now())) as "createdOn",
    '' as "assignedReviewer"
from (select source.concept_id, source.concept_name, source.concept_code, source.vocabulary_id,
             answer.concept_code as answer_code, answer.concept_name as answer_name,
             regexp_replace(answer.concept_code, '^\d+-', '') as answer_value
      from vocab.concept source
               left join vocab.concept_relationship cra on cra.concept_id_1 = concept_id and
                                                           cra.relationship_id like 'Has Answer'
               left join vocab.concept answer on concept_id_2 = answer.concept_id
     ) as source
         left join vocab.concept_relationship on
            concept_id_1 = concept_id and
            relationship_id like 'Maps to%'
         left join vocab.concept target on concept_id_2 = target.concept_id
where source.vocabulary_id = 'UK Biobank' and (answer_value is null or position('-' in answer_value) = 0)
  and source.concept_code in (
                              '22158',
                              '22178',
                              '22151',
                              '22171',
                              '22161',
                              '22181',
                              '22156',
                              '22176',
                              '22152',
                              '22172',
                              '10844',
                              '22159',
                              '22179',
                              '22155',
                              '22175',
                              '22160',
                              '22180',
                              '22148',
                              '22168',
                              '22153',
                              '22173',
                              '22157',
                              '22177',
                              '22154',
                              '22174',
                              '22149',
                              '22169',
                              '22150',
                              '22170',
-- '4022',
-- '4689',
-- '4056',
-- '3992',
-- '4012',
-- '4041',
-- '3894',
                              '40002',
                              '22147',
                              '22167',
-- '4700',
                              '3627',
                              '22146',
                              '22166',
-- '2976',
                              '3005',
                              '6151',
-- '3786',
                              '20544',
                              '22126',
                              '22127',
                              '22128',
                              '22129',
                              '22130',
                              '22131',
                              '22132',
                              '22133',
                              '22134',
                              '22135',
                              '22136',
                              '22137',
                              '22138',
                              '22139',
                              '22140',
                              '22141',
                              '22506',
                              '3761',
                              '20403',
-- '2966',
                              '21024',
                              '26410',
                              '6150',
                              '23099',
-- '2443',
-- '2453',
-- '2463',
-- '2473',
                              '20117',
                              '20116',
                              '6152',
                              '21001',
                              '22420'
-- '2986'
    )
;