# Database connection
database:
  host: 'localhost'
  port: 6000
  database_name: 'ukb'
  username: 'postgres'
  # Comment out password to provide at runtime
  password: 'postgres'

run_options:
  source_data_folder: './resources/synthetic_data'
  debug_mode: False
